In [1]:
import numpy as np
from scipy.special import logsumexp

In [2]:
a = [0, 1,2 ]
a1 = [0, 1]

In [3]:
np.log(np.sum(np.exp(a)))

2.40760596444438

In [4]:
logsumexp(a)

2.4076059644443806

In [5]:
a

[0, 1, 2]

In [6]:
np.max(a1) + np.log(1 + np.exp(np.sum(a1) - 2 * np.max(a1)))

1.3132616875182228

In [7]:
a2 = [1.31326, 2]

In [8]:
np.max(a2) + np.log(1 + np.exp(np.sum(a2) - 2 * np.max(a2)))

2.4076053995327102

In [9]:
np.max(a2) + np.log(1 + np.exp(np.sum(a2) - 2 * np.max(a2)))

2.4076053995327102

In [10]:
logsumexp(a)

2.4076059644443806

In [11]:
a

[0, 1, 2]

In [12]:
np.max(a1) + np.log(1 + np.exp(np.sum(a1) - 2 * np.max(a1)))

1.3132616875182228

In [13]:
a2 = [1.31326, 2]

In [14]:
np.max(a2) + np.log(1 + np.exp(np.sum(a2) - 2 * np.max(a2)))

2.4076053995327102

In [15]:
def neglogsigmoid(x):
  return np.log(1 + np.exp(-x))

neglogsigmoid(4) - 0.0180588

9.112791780977944e-05

In [16]:
def lse(arr) :
    lse_value = np.max(arr) + np.log(1 + np.exp(np.sum(arr) - 2 * np.max(arr)))
    return lse_value

In [17]:
# lse() : python plaintext, X.xx : MPC using NegLogSigmoid
lse([1,4]) - 4.04812

0.0004673515737421141

In [18]:
lse([0,1]) - 1.31195

0.0013116875182228593

In [19]:
lse([2,3]) - 3.31196

0.0013016875182230159

In [20]:
lse([5,10]) - 10.0065

0.00021534848911741733

In [21]:
lse([-1,15]) - 14.9998

0.0002001125351682731

In [22]:
print(logsumexp([1,2]))
print(logsumexp([3,4]))
print(logsumexp([1,2,3,4]))

2.313261687518223
4.313261687518223
4.440189698561196


In [23]:
print(lse([1,2]))
print(lse([3,4]))
print(lse([2.3132616875,4.3132616875]))

2.313261687518223
4.313261687518223
4.440189698542972


In [24]:
#[-200,200]
-200 + np.log(1 + np.exp(400))

200.0

In [25]:
#[200,-200]
200 + np.log(1 + np.exp(-400))

200.0

In [2]:
def softmax(x) :
    return np.exp(x)/np.sum(np.exp(x))

In [27]:
print(logsumexp([1,2]))
print(softmax([1,2]))


print(logsumexp([1,4]))
print(softmax([1,4]))


print(logsumexp([1,2,3,4]))
print(softmax([1,2,3,4]))
print(softmax([1,2]))
print(softmax([3,4]))

2.313261687518223
[0.26894142 0.73105858]
4.048587351573742
[0.04742587 0.95257413]
4.440189698561196
[0.0320586  0.08714432 0.23688282 0.64391426]
[0.26894142 0.73105858]
[0.26894142 0.73105858]


In [ ]:
input_x = [1,2]
print(logsumexp(input_x))
print(softmax(input_x))

# Thu Sep  3 13:56:34 2020 | lse :
# 2.31266
#
# Thu Sep  3 13:56:34 2020 | lse_g :
# 0.267593	0.732407

In [32]:
input_x = [1,2,3,4]
print(logsumexp(input_x))
print(softmax(input_x))
# Thu Sep  3 13:58:27 2020 | lse :
# 4.44421
#
# Thu Sep  3 13:58:27 2020 | lse_g :
# 0.0946236	0.905376
#
# Thu Sep  3 13:58:27 2020 | lse_g :
# 0.025322	0.0693016	0.242275	0.663101

4.440189698561196
[0.0320586  0.08714432 0.23688282 0.64391426]


In [35]:
input_x = [1,2,3,4,5,6,7,8]
print(logsumexp(input_x))
print(softmax(input_x))

8.458339626479004
[5.76612770e-04 1.56739601e-03 4.26062410e-03 1.15815771e-02
 3.14819905e-02 8.55769227e-02 2.32622194e-01 6.32332683e-01]


In [4]:
input_x = [0.1,-0.1,-0.5,0.7,0.4,0.3]
print(logsumexp(input_x))
print(softmax(input_x))

# approx_softmax = [
#     0.000419617,
#     0.00129318,
#     0.00352478,
#     0.010849,
#     0.0257301,
#     0.0792694,
#     0.215389,
#     0.663521
#     ]
# print(softmax(input_x) - approx_softmax)
# relative error
# accuracy 1 %
0.01
# do pair programming

2.0111593830024064
[0.1479088  0.12109749 0.08117407 0.26950741 0.199656   0.18065622]


0.01

In [ ]:
# NegLogSigmoid


